/*
 * xpms.c - 2022-2025 Will Brokenbourgh
 * part of the SpiritVNC - Gtk project
 *
*/

/*
 * (C) Will Brokenbourgh
 *
 * Redistribution and use in source and binary forms, with or without modification, are
 * permitted provided that the following conditions are met:
 *
 * 1. Redistributions of source code must retain the above copyright notice, this list of
 * conditions and the following disclaimer.
 *
 * 2. Redistributions in binary form must reproduce the above copyright notice, this list of
 * conditions and the following disclaimer in the documentation and/or other materials provided
 * with the distribution.
 *
 * 3. Neither the name of the copyright holder nor the names of its contributors may be used
 * to endorse or promote products derived from this software without specific prior written
 * permission.
 *
 * THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS "AS IS" AND ANY EXPRESS
 * OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE IMPLIED WARRANTIES OF
 * MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE ARE DISCLAIMED. IN NO EVENT SHALL THE
 * COPYRIGHT HOLDER OR CONTRIBUTORS BE LIABLE FOR ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL,
 * EXEMPLARY, OR CONSEQUENTIAL DAMAGES (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE
 * GOODS OR SERVICES; LOSS OF USE, DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER CAUSED
 * AND ON ANY THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY, OR TORT (INCLUDING
 * NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE OF THIS SOFTWARE, EVEN IF ADVISED
 * OF THE POSSIBILITY OF SUCH DAMAGE.
 */

#include "xpms.h"

const char * xpmBlank[] = {
"16 16 1 1",
" 	c None",
"                ",
"                ",
"                ",
"                ",
"                ",
"                ",
"                ",
"                ",
"                ",
"                ",
"                ",
"                ",
"                ",
"                ",
"                ",
"                "};


const char * xpmDisconnected[] = {
  "16 16 2 1",
  "   c None",
  ".  c #D5D5D5",
  "                ",
  "                ",
  "                ",
  "   ..........   ",
  "   .        .   ",
  "   .        .   ",
  "   .        .   ",
  "   .        .   ",
  "   .        .   ",
  "   .        .   ",
  "   .        .   ",
  "   .        .   ",
  "   ..........   ",
  "                ",
  "                ",
  "                "
};

const char * xpmConnected[] = {
  "16 16 2 1",
  "   c None",
  ".  c #58BF55",
  "                ",
  "                ",
  "                ",
  "   ..........   ",
  "   ..........   ",
  "   ..........   ",
  "   ..........   ",
  "   ..........   ",
  "   ..........   ",
  "   ..........   ",
  "   ..........   ",
  "   ..........   ",
  "   ..........   ",
  "                ",
  "                ",
  "                "
};

const char * xpmWait[] = {
  "16 16 5 1",
  "   c None",
  ".  c #666666",
  "+  c #D5D5D5",
  "@  c #E8E8E8",
  "#  c #EFEFEF",
  "                ",
  "                ",
  "                ",
  "   ++++++++++   ",
  "   +@##..##@+   ",
  "   +###..###+   ",
  "   +###..###+   ",
  "   +###....#+   ",
  "   +###....#+   ",
  "   +########+   ",
  "   +########+   ",
  "   +@######@+   ",
  "   ++++++++++   ",
  "                ",
  "                ",
  "                "
};

const char * xpmTimeout[] = {
  "16 16 2 1",
  "   c None",
  ".  c #BFBFBF",
  "                ",
  "                ",
  "                ",
  "   ..........   ",
  "   ..........   ",
  "   ..........   ",
  "   ..........   ",
  "   ..........   ",
  "   ..........   ",
  "   ..........   ",
  "   ..........   ",
  "   ..........   ",
  "   ..........   ",
  "                ",
  "                ",
  "                "
};

const char * xpmError[] = {
  "16 16 3 1",
  "   c None",
  ".  c #D4D4D4",
  "+  c #F36F6E",
  "                ",
  "                ",
  "                ",
  "   ..........   ",
  "   .++++++++.   ",
  "   .++++++++.   ",
  "   .++++++++.   ",
  "   .++++++++.   ",
  "   .++++++++.   ",
  "   .++++++++.   ",
  "   .++++++++.   ",
  "   .++++++++.   ",
  "   ..........   ",
  "                ",
  "                ",
  "                "
};

const char * xpmSpiritvnc[] = {
"48 48 207 2",
"  	c None",
". 	c #36A3A3",
"+ 	c #3FBDBD",
"@ 	c #4FC4C4",
"# 	c #52C5C5",
"$ 	c #50C5C5",
"% 	c #47C2C2",
"& 	c #37A6A6",
"* 	c #2E8B8B",
"= 	c #3FBEBE",
"- 	c #3DB7B7",
"; 	c #256E6E",
"> 	c #51C5C5",
", 	c #123737",
"' 	c #4EC4C4",
") 	c #020505",
"! 	c #35A0A0",
"~ 	c #000000",
"{ 	c #4AC3C3",
"] 	c #277676",
"^ 	c #359E9E",
"/ 	c #2D8787",
"( 	c #1D5757",
"_ 	c #0A1F1F",
": 	c #061111",
"< 	c #071414",
"[ 	c #0D2626",
"} 	c #113434",
"| 	c #1A4E4E",
"1 	c #309191",
"2 	c #1E5959",
"3 	c #4BC3C3",
"4 	c #0A1D1D",
"5 	c #030909",
"6 	c #184747",
"7 	c #297B7B",
"8 	c #4CC3C3",
"9 	c #2C8484",
"0 	c #061212",
"a 	c #226565",
"b 	c #3EB9B9",
"c 	c #349C9C",
"d 	c #49C2C2",
"e 	c #3DB8B8",
"f 	c #0B2222",
"g 	c #3CB3B3",
"h 	c #329595",
"i 	c #2B8181",
"j 	c #329696",
"k 	c #6ECFCF",
"l 	c #95DCDC",
"m 	c #44C1C1",
"n 	c #36A1A1",
"o 	c #3EBABA",
"p 	c #4DC4C4",
"q 	c #5CC9C9",
"r 	c #051010",
"s 	c #5FCACA",
"t 	c #2B8282",
"u 	c #7AD3D3",
"v 	c #8DD9D9",
"w 	c #8BD8D8",
"x 	c #78D2D2",
"y 	c #2D8686",
"z 	c #309090",
"A 	c #84D6D6",
"B 	c #329797",
"C 	c #38A9A9",
"D 	c #267373",
"E 	c #86D7D7",
"F 	c #2F8E8E",
"G 	c #184848",
"H 	c #1A4F4F",
"I 	c #2F8D8D",
"J 	c #53C6C6",
"K 	c #267171",
"L 	c #56C7C7",
"M 	c #349D9D",
"N 	c #071616",
"O 	c #8AD8D8",
"P 	c #236A6A",
"Q 	c #287979",
"R 	c #42C0C0",
"S 	c #41C0C0",
"T 	c #319494",
"U 	c #76D1D1",
"V 	c #246B6B",
"W 	c #2C8383",
"X 	c #8FDADA",
"Y 	c #1D5656",
"Z 	c #8ED9D9",
"` 	c #6BCECE",
" .	c #67CCCC",
"..	c #83D6D6",
"+.	c #7CD3D3",
"@.	c #43C0C0",
"#.	c #2A7E7E",
"$.	c #38A8A8",
"%.	c #7BD3D3",
"&.	c #133838",
"*.	c #236969",
"=.	c #48C2C2",
"-.	c #93DBDB",
";.	c #081818",
">.	c #257070",
",.	c #206161",
"'.	c #89D8D8",
").	c #113232",
"!.	c #36A2A2",
"~.	c #277474",
"{.	c #91DADA",
"].	c #90DADA",
"^.	c #339999",
"/.	c #60CACA",
"(.	c #226666",
"_.	c #0B2020",
":.	c #226767",
"<.	c #339898",
"[.	c #77D2D2",
"}.	c #287777",
"|.	c #308F8F",
"1.	c #3AAEAE",
"2.	c #2F8C8C",
"3.	c #349B9B",
"4.	c #2C8585",
"5.	c #297A7A",
"6.	c #216262",
"7.	c #3EBBBB",
"8.	c #6ACDCD",
"9.	c #010202",
"0.	c #174646",
"a.	c #267272",
"b.	c #6DCECE",
"c.	c #3DB6B6",
"d.	c #79D2D2",
"e.	c #246D6D",
"f.	c #72D0D0",
"g.	c #92DBDB",
"h.	c #091C1C",
"i.	c #39AAAA",
"j.	c #45C1C1",
"k.	c #1B5252",
"l.	c #2E8989",
"m.	c #040D0D",
"n.	c #5BC8C8",
"o.	c #030A0A",
"p.	c #3AAFAF",
"q.	c #2E8A8A",
"r.	c #143B3B",
"s.	c #75D1D1",
"t.	c #164141",
"u.	c #123636",
"v.	c #58C7C7",
"w.	c #80D5D5",
"x.	c #1E5A5A",
"y.	c #74D1D1",
"z.	c #050F0F",
"A.	c #87D7D7",
"B.	c #2B8080",
"C.	c #7ED4D4",
"D.	c #256F6F",
"E.	c #1F5C5C",
"F.	c #339A9A",
"G.	c #319292",
"H.	c #1D5858",
"I.	c #030808",
"J.	c #010303",
"K.	c #3CB5B5",
"L.	c #1C5353",
"M.	c #71D0D0",
"N.	c #39ACAC",
"O.	c #0D2727",
"P.	c #38A7A7",
"Q.	c #010404",
"R.	c #091A1A",
"S.	c #154040",
"T.	c #1E5B5B",
"U.	c #0E2929",
"V.	c #39ABAB",
"W.	c #3BB2B2",
"X.	c #82D5D5",
"Y.	c #63CBCB",
"Z.	c #61CACA",
"`.	c #103030",
" +	c #216464",
".+	c #194A4A",
"++	c #8CD9D9",
"@+	c #319393",
"#+	c #236868",
"$+	c #359F9F",
"%+	c #0E2B2B",
"&+	c #64CBCB",
"*+	c #3CB4B4",
"=+	c #143C3C",
"-+	c #0B2121",
";+	c #174545",
">+	c #3AADAD",
",+	c #206060",
"'+	c #205F5F",
")+	c #1C5454",
"!+	c #0D2828",
"~+	c #0F2E2E",
"{+	c #000101",
"]+	c #0C2424",
"^+	c #1F5E5E",
"/+	c #246C6C",
"(+	c #020606",
"                                                                                                ",
"                                                                                                ",
"                                  . + @ # # # # # # # # # # # $ % & *                           ",
"                              = $ # # # # # # # # # # # # # # # # # # # @ -                     ",
"                          - # # # # # # # # # # # # # # # # # # # # # # # # ;                   ",
"                        > # # # # # # # # # # # # # # # # # # # # # # # # # ,                   ",
"                      > # # # # # # # # # # # # # # # # # # # # # # # # # ' )                   ",
"                    > # # # # # # # # # # # # # # # # # # # # # # # # # # ! ~                   ",
"                  { # # # # # # # # # # # # # # # # # # # # # # # # # # # ] ~                   ",
"                ^ # # # # # # # # # # @ / ( , _ : < [ } | ; 1 { # # # # # 2                     ",
"                3 # # # # # # # # # / 4 ~ ~                   5 6 7 3 # # ,                     ",
"                # # # # $ @ 8 8 @ 9 ~ ~                             0 a b                       ",
"              c # # # @ d = e e = f ~                                                           ",
"              & $ # $ d g h i 9 j ~ ~                                                           ",
"    k l l m   n 8 $ 8 o 1 p l l q r ( l {               s l l t             ; { u v w x > y     ",
"    z l l A 5 B d @ d C D E l l F G H l l I             J l l K           L l l l l l l l l M   ",
"    N O l l P Q R 8 S T h l l U V W ] l l X Y           ' l l P         k l l l Z `  ...l +.    ",
"      @.l l m Y - % g #.L l l $.W F 9 l l l %.&.        p l l *.      =.l l -.C ;.      >.F     ",
"      ,.l l '.).$.+ !.~.{.l ].~.^.h 9 l l l l /.K 9 (._.{ l l :.    H l l l <.                  ",
"        [.l l }.|.1.2.& l l # #.C 3.4.l l l l l b 5.B 5.8 l l 6.    7.l l 8.9.                  ",
"        . l l > 0.j a.b.l l 2.j c.M 4.l l d.-.l l T ] V 8 l l e.) ~ f.l l z                     ",
"        } g.l X h.*.Q l l u a.i.+ ^ y l l j.^.l l w >.k.{ l l l.V m.{.l l k.                    ",
"          n.l l i o.g l l p.q.b R n y l l { r.> l l s.t.j.l l y i ,.l l l u.                    ",
"          t l l v.) w.l g.] n m m n y l l p x.6.y.l l ' R l l y W :.-.l l t.                    ",
"          z.A.l g.Q l l > k.g d m n y l l $ K B.Q '.l l v l l y 4.; C.l l K                     ",
"            7.l l w l l D.~ _ E./ F.y l l > 7 ^ / G.l l l l l l.q.7 J l l S                     ",
"            H.l l l l w.I.        J.( l l $ B.p.i.#.K.l l l l l.|.2.3.l l {.L.                  ",
"              M.l l l N.            k.l l =.O.a.+ P.D n.l l l l.j n ] u l l E }.Q.    R.P.w     ",
"              M l l -.S.            T.l l 8 ~   U.V.c D d.l l 2.3.W.h q.Z l l l X.Y.` X l l Z.  ",
"              `.-.l s                +l l #       .+b T t ++l @+!.= K.2.#+..l l l l l l l X $+  ",
"                Z.l 1               ] l l /.        { K.F C l $.p.% % K.%+;.3.&+..g.E ` *+=+    ",
"                                                    @ d c.^ B $.S 8 @ d -+                      ",
"        % c.                                      B.# @ { @.S m 8 $ # =.~                       ",
"        8 # $ @+                                  8 # # $ @ @ $ $ # # t ~                       ",
"        $ # # # > C K                           8 # # # # # # # # # # ;+                        ",
"        # # # # # # # ' >+I               @+R # # # # # # # # # # # n ~                         ",
"        # # # # # # # # # # # # # # # # # # # # # # # # # # # # # > ,                           ",
"        # # # # # # # # # # # # # # # # # # # # # # # # # # # # # ,+~                           ",
"        # # # # # # # # # # # # # # # # # # # # # # # # # # # # >.~                             ",
"        # # # # # # # # # # # # # # # # # # # # # # # # # # > '+~                               ",
"        # # # # # # # # # # # # # # # # # # # # # # # # # 3.%+~                                 ",
"          y R # # # # # # # # # # # # # # # # # # # # !.)+J.                                    ",
"              !+2 #.p.' # # # # # # # # # # # p c K ~+~ ~                                       ",
"                      {+]+t.)+^+a /+e.6.H.| u.(+~ ~                                             ",
"                                                                                                ",
"                                                                                                ",
"                                                                                                ",
"                                                                                                "};
